version: '20.0.7'

services:
  web:
    build: .
    command: python /100DaysOfDjango/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/100DaysOfDjango
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data:
